security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        slab_user:
            id: Slab\Component\Security\Provider\UserProvider
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: /logout

            # activate different ways to authenticate
            guard:
                authenticators:
                    - Slab\Component\Security\Guard\LoginFormAuthenticator
                provider: slab_user

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }