##
# Entity User
#
# @package     Slab\Component\Security\Entity
# @author      Didier Youn <didier.youn@gmail.com>
# @copyright   Copyright (c) 2018 Slabprea
##
Slab\Component\Security\Entity\User:
    type: entity
    table: slab_user
    repositoryClass: Slab\Component\Security\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            unique: true
            length: 255
            nullable: false
        email:
            type: string
            unique: true
            length: 255
            nullable: false
        firstName:
            type: string
            unique: false
            length: 255
            column: firstname
            nullable: true
        lastName:
            type: string
            unique: false
            length: 255
            column: lastname
            nullable: true
        password:
            type: text
            unique: false
            nullable: false
        salt:
            type: text
            unique: false
            nullable: true
        isActive:
            type: boolean
            nullable: false
            column: is_active